### ISSUE TITLE
Template fails to run after setup

### ISSUE THREAD

**Issue by austincrim-pfg** [cloudflare/cobol-worker-template#7]
After running `wrangler generate` with this template and running `npm run dev`, the worker fails with a 500 status code.
Here's the error output:
```bash
"A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise\'s request context have already finished."
[2021-04-08 08:16:22] GET cloud-cobol.austin-crim.workers.dev/ HTTP/1.1 500 Internal Server Error
"Module.instantiateWasm callback failed with error: ReferenceError: wasm is not defined"
```

**environment**
macOS: 10.15.7
wrangler: 1.15.0
node: 14.16.0
npm: 6.14.11
docker: 20.10.5

**Comment by xtuc** [comment]
This regression was likely introduced by https://github.com/cloudflare/wrangler/pull/1730, where the `wasm` binding was renamed to `WASM_MODULE`, we will need to change it here https://github.com/cloudflare/cobol-worker-template/blob/b65b3d2e960e69b8a679f3391af987c2e5cf88c3/src/index.js#L16. Would you mind sending a PR?
